services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=dio
        - MONGO_INITDB_PASSWORD=dio
    ports:
        - "27017:27017"
    volumes:
        - C:/Temp/mongo_db:/data/db
